[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$QygFYGwtZey9957zPse49w$cW/xnfpVe.gjx/cjZfjx747XfZYpFo.U4lKdSFI8W6GGtcgLorF5MQ4nq8mlme1ioOgi7MlrSmP27dxfiTRkDw
